
np_seed: 3197
torch_seed: 1921
gpu: True

train:
  epochs: 50
  petrained: None

eval:
  test_aug: False


optimizer:
  opt: sgd
  lr: 0.01
  weight_decay: 0.0005
  momentum: 0.937
  lr_schedular: cosine
  warmup_epochs: 2


dataset:
  root: ./data/train
  ratio: 0.9
  labels: ["cat", "dog"]
  batch_size: 16
  size: [224, 224] # size (w, h)
  fliplr: 0.5
  flipud: 0
  scale: [0.7, 1.0]
  rotation: 30
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]