

model:
  - [-1,1, Stem, [3,32]] ## stride = 4
  - [-1,1, ResNeXtBlock, [32, 4, 8, 1]]
  - [-1,1, BaseConv, [32, 64, 1, 1]]
  - [-1,1, ResNeXtBlock, [64, 4, 32, 2]] ## stride = 8
  - [-1,2, ResNeXtBlock, [64, 4, 32, 1]] 
  - [-1,1, BaseConv, [64, 128, 1, 1]]
  - [-1,1, ResNeXtBlock, [128, 4, 32, 2]] ## stride = 16
  - [-1,3, ResNeXtBlock, [128, 4, 32, 1]]
  - [-1,1, ResNeXtBlock, [128, 4, 32, 2]] ## stride = 32
  - [-1,1, ResNeXtBlock, [128, 4, 32, 1]]
  - [-1,1, ClassificationHead, [128, [128, 64], 2]]



